# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

plugins:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'vendor/**/*'

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/routes.rb'

Metrics/ClassLength:
  Max: 150

Metrics/MethodLength:
  Max: 15
  Exclude:
    - 'spec/**/*'

Metrics/ParameterLists:
  Max: 8

Layout/LineLength:
  Max: 150

RSpec/MultipleExpectations:
  Max: 10

RSpec/ExampleLength:
  Max: 15

Lint/RescueException:
  Enabled: false

Lint/UselessRescue:
  Enabled: false
